[package]
name = "call23re/inserter"
version = "1.0.0"
realm = "shared"
registry = "https://github.com/upliftgames/wally-index"

[dependencies]
roact = "roblox/roact@1.4.2"
studiocomponents = "sircfenner/studiocomponents@0.1.1"