local AssetTypes = {
	[2] = "GraphicTShirt",
	[8] = "HatAccessory",
	[11] = "Shirt",
	[12] = "Pants",
	[17] = "Head",
	[18] = "Face",
	[27] = "Torso",
	[28] = "RightArm",
	[29] = "LeftArm",
	[30] = "LeftLeg",
	[31] = "RightLeg",
	[41] = "HairAccessory",
	[42] = "FaceAccessory",
	[43] = "NeckAccessory",
	[44] = "ShoulderAccessory",
	[45] = "FrontAccessory",
	[46] = "BackAccessory",
	[47] = "WaistAccessory",
	[48] = "ClimbAnimation",
	[49] = "DeathAnimation",
	[50] = "FallAnimation",
	[51] = "IdleAnimation",
	[52] = "JumpAnimation",
	[53] = "RunAnimation",
	[54] = "SwimAnimation",
	[55] = "WalkAnimation",
	[56] = "PoseAnimation",
	[64] = "TShirtAccessory",
	[65] = "ShirtAccessory",
	[66] = "PantsAccessory",
	[67] = "JacketAccessory",
	[68] = "SweaterAccessory",
	[69] = "ShortsAccessory",
	[70] = "LeftShoeAccessory",
	[71] = "RightShoeAccessory",
	[72] = "DressSkirtAccessory"
}

return {
	AssetTypes = AssetTypes
}